const items = @import("items.zig");
const Item = items.Item;
const weapons = @import("weapons.zig");

// Adventuring gear definitions.
// Data source: 2014 Player's Handbook equipment tables as represented by
// dnd5e.wikidot.com/adventuring-gear, plus the Dragonlance-specific entries.
//
// Items without an explicit source price intentionally have shop_entry = null.
// Bundle prices use ShopEntry.count rather than turning a bundle into one Item.
// Descriptions are concise paraphrases, not source text.

pub const string_10_ft: Item = Item.compInit(
    "String (10 ft)",
    .phb14,
    false,
    null,
    null,
    .{ .unit = .foot, .count = 10 },
    null,
    null,
    null,
    "A ten-foot length of string.",
    null,
    null,
    null,
    null,
);

pub const alms_box: Item = Item.compInit(
    "Alms Box",
    .phb14,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    "A small box intended for collecting alms.",
    null,
    null,
    null,
    null,
);

pub const incense_block: Item = Item.compInit(
    "Block of Incense",
    .phb14,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    "A block of incense.",
    null,
    null,
    null,
    null,
);

pub const censer: Item = Item.compInit(
    "Censer",
    .phb14,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    "A vessel used for burning incense.",
    null,
    null,
    null,
    null,
);

pub const vestments: Item = Item.compInit(
    "Vestments",
    .phb14,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    "Religious vestments.",
    null,
    null,
    null,
    null,
);

pub const small_bag_of_sand: Item = Item.compInit(
    "Small Bag of Sand",
    .phb14,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    "A small bag containing sand.",
    null,
    null,
    null,
    null,
);

pub const small_knife: Item = Item.compInit(
    "Small Knife",
    .phb14,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    "A small utility knife.",
    null,
    null,
    null,
    null,
);

pub const abacus: Item = Item.compInit(
    "Abacus",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    null,
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    null,
    "A counting frame.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const bedroll: Item = Item.compInit(
    "Bedroll",
    .phb14,
    false,
    .{ .unit = .pound, .count = 7.0 },
    null,
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const bell: Item = Item.compInit(
    "Bell",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const blanket: Item = Item.compInit(
    "Blanket",
    .phb14,
    false,
    .{ .unit = .pound, .count = 3.0 },
    null,
    null,
    .{ .currency = .silver, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .silver, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const block_and_tackle: Item = Item.compInit(
    "Block and Tackle",
    .phb14,
    false,
    .{ .unit = .pound, .count = 5.0 },
    null,
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    null,
    "A pulley-and-cable set that increases lifting leverage.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const book: Item = Item.compInit(
    "Book",
    .phb14,
    false,
    .{ .unit = .pound, .count = 5.0 },
    null,
    null,
    .{ .currency = .gold, .count = 25 },
    null,
    null,
    "A bound book containing text, illustrations, notes, or other written material.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 25 }, .count = 1, .wrapping_container = null },
);

pub const candle: Item = Item.compInit(
    "Candle",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .copper, .count = 1 },
    null,
    null,
    "Burns for about 1 hour and provides a small area of light.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .copper, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const chain_10_ft: Item = Item.compInit(
    "Chain (10 ft)",
    .phb14,
    false,
    .{ .unit = .pound, .count = 10.0 },
    null,
    .{ .unit = .foot, .count = 10 },
    .{ .currency = .gold, .count = 5 },
    null,
    null,
    "A ten-foot chain; it has 10 hit points and can be burst with a difficult Strength check.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const chalk: Item = Item.compInit(
    "Chalk (1 pc)",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .copper, .count = 1 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .copper, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const component_pouch: Item = Item.compInit(
    "Component Pouch",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    null,
    null,
    .{ .currency = .gold, .count = 25 },
    null,
    null,
    "A compartmentalized, watertight belt pouch for spell components that do not have a specified cost.",
    null,
    null,
    .{ .small_container = .{ .contents = null, .valid_items = .{ .items = true, .fluids = false } } },
    .{ .cost = .{ .currency = .gold, .count = 25 }, .count = 1, .wrapping_container = null },
);

pub const fishing_tackle: Item = Item.compInit(
    "Fishing Tackle",
    .phb14,
    false,
    .{ .unit = .pound, .count = 4.0 },
    null,
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    null,
    "A kit with a rod, line, hooks, sinkers, floats, lures, and narrow netting.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const grappling_hook: Item = Item.compInit(
    "Grappling Hook",
    .phb14,
    false,
    .{ .unit = .pound, .count = 4.0 },
    null,
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const hammer: Item = Item.compInit(
    "Hammer",
    .phb14,
    false,
    .{ .unit = .pound, .count = 3.0 },
    null,
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const hourglass: Item = Item.compInit(
    "Hourglass",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .gold, .count = 25 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 25 }, .count = 1, .wrapping_container = null },
);

pub const ink_bottle_1_oz: Item = Item.compInit(
    "Ink Bottle (1 oz)",
    .phb14,
    false,
    null,
    .{ .unit = .ounce, .count = 1 },
    null,
    null,
    null,
    null,
    "A small bottle sized to hold one ounce of ink.",
    null,
    null,
    .{ .fluid_container = .{ .fluid = null, .volume_limit = .{ .unit = .ounce, .count = 1 }, .weight_full = null, .volume_of_contents = null } },
    null,
);

pub const ink: Item = Item.compInit(
    "Ink (1 oz)",
    .phb14,
    false,
    null,
    .{ .unit = .ounce, .count = 1 },
    null,
    .{ .currency = .gold, .count = 10 },
    null,
    null,
    null,
    null,
    null,
    .{ .fluid = .{ .default_container = ink_bottle_1_oz.hash, .weight = null } },
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = ink_bottle_1_oz.hash },
);

pub const ink_pen: Item = Item.compInit(
    "Ink Pen",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .copper, .count = 2 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .copper, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const ladder_10_ft: Item = Item.compInit(
    "Ladder (10 ft)",
    .phb14,
    false,
    .{ .unit = .pound, .count = 25.0 },
    null,
    .{ .unit = .foot, .count = 10 },
    .{ .currency = .silver, .count = 1 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .silver, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const lock: Item = Item.compInit(
    "Lock",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .gold, .count = 10 },
    null,
    null,
    "Supplied with a key; a typical lock can be picked with thieves' tools at a moderate difficulty.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = null },
);

pub const magnifying_glass: Item = Item.compInit(
    "Magnifying Glass",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .gold, .count = 100 },
    null,
    null,
    "A lens for inspecting small details and, in strong sunlight, focusing light to start a fire.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 100 }, .count = 1, .wrapping_container = null },
);

pub const manacles: Item = Item.compInit(
    "Manacles",
    .phb14,
    false,
    .{ .unit = .pound, .count = 6.0 },
    null,
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    null,
    "Metal restraints with a key; escaping, breaking, or picking them requires a difficult check.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const mess_kit: Item = Item.compInit(
    "Mess Kit",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .silver, .count = 2 },
    null,
    null,
    "A compact tin eating set whose two halves can serve as cookware and dishes.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .silver, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const miners_pick: Item = Item.compInit(
    "Miner's Pick",
    .phb14,
    false,
    .{ .unit = .pound, .count = 10.0 },
    null,
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const paper: Item = Item.compInit(
    "Paper (1 sheet)",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .silver, .count = 2 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .silver, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const parchment: Item = Item.compInit(
    "Parchment (1 sheet)",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .silver, .count = 1 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .silver, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const pouch: Item = Item.compInit(
    "Pouch",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .silver, .count = 5 },
    null,
    "Capacity: about 1/5 cubic foot or 6 pounds of gear; commonly holds up to 20 sling bullets or 50 blowgun needles.",
    null,
    null,
    null,
    .{ .small_container = .{ .contents = null, .valid_items = .{ .items = true, .fluids = false } } },
    .{ .cost = .{ .currency = .silver, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const perfume: Item = Item.compInit(
    "Perfume (vial)",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    .{ .fluid = .{ .default_container = vial.hash, .weight = null } },
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = vial.hash },
);

pub const piton: Item = Item.compInit(
    "Piton",
    .phb14,
    false,
    .{ .unit = .pound, .count = 0.25 },
    null,
    null,
    .{ .currency = .copper, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .copper, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const pole_10_ft: Item = Item.compInit(
    "Pole (10 ft)",
    .phb14,
    false,
    .{ .unit = .pound, .count = 7.0 },
    null,
    .{ .unit = .foot, .count = 10 },
    .{ .currency = .copper, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .copper, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const portable_ram: Item = Item.compInit(
    "Portable Ram",
    .phb14,
    false,
    .{ .unit = .pound, .count = 35.0 },
    null,
    null,
    .{ .currency = .gold, .count = 4 },
    null,
    null,
    "Provides leverage when breaking down doors; another creature can assist its use.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 4 }, .count = 1, .wrapping_container = null },
);

pub const ration: Item = Item.compInit(
    "Rations (1 day)",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    null,
    null,
    .{ .currency = .silver, .count = 5 },
    null,
    null,
    "Dry, travel-stable food sufficient for one day.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .silver, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const hempen_rope_50_ft: Item = Item.compInit(
    "Hempen Rope (50 ft)",
    .phb14,
    false,
    .{ .unit = .pound, .count = 10.0 },
    null,
    .{ .unit = .foot, .count = 50 },
    .{ .currency = .gold, .count = 1 },
    null,
    null,
    "Fifty feet of hemp rope.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const silk_rope_50_ft: Item = Item.compInit(
    "Silk Rope (50 ft)",
    .phb14,
    false,
    .{ .unit = .pound, .count = 5.0 },
    null,
    .{ .unit = .foot, .count = 50 },
    .{ .currency = .gold, .count = 10 },
    null,
    null,
    "Fifty feet of silk rope.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = null },
);

pub const sealing_wax: Item = Item.compInit(
    "Sealing Wax",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .silver, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .silver, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const shovel: Item = Item.compInit(
    "Shovel",
    .phb14,
    false,
    .{ .unit = .pound, .count = 5.0 },
    null,
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const signal_whistle: Item = Item.compInit(
    "Signal Whistle",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .copper, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .copper, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const signet_ring: Item = Item.compInit(
    "Signet Ring",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const sledgehammer: Item = Item.compInit(
    "Sledgehammer",
    .phb14,
    false,
    .{ .unit = .pound, .count = 10.0 },
    null,
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const spellbook: Item = Item.compInit(
    "Spellbook",
    .phb14,
    false,
    .{ .unit = .pound, .count = 3.0 },
    null,
    null,
    .{ .currency = .gold, .count = 50 },
    null,
    null,
    "A leather-bound tome with 100 blank vellum pages suitable for recording spells.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 50 }, .count = 1, .wrapping_container = null },
);

pub const iron_spike: Item = Item.compInit(
    "Iron Spike",
    .phb14,
    false,
    .{ .unit = .pound, .count = 0.5 },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 10, .wrapping_container = null },
);

pub const spyglass: Item = Item.compInit(
    "Spyglass",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .gold, .count = 1000 },
    null,
    null,
    "Magnifies viewed objects to about twice their apparent size.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1000 }, .count = 1, .wrapping_container = null },
);

pub const two_person_tent: Item = Item.compInit(
    "Two-Person Tent",
    .phb14,
    false,
    .{ .unit = .pound, .count = 20.0 },
    null,
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const whetstone: Item = Item.compInit(
    "Whetstone",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .copper, .count = 1 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .copper, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const backpack: Item = Item.compInit(
    "Backpack",
    .phb14,
    false,
    .{ .unit = .pound, .count = 5.0 },
    null,
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    "Capacity: 1 cubic foot or 30 pounds of gear. Items such as a bedroll or rope can be strapped outside.",
    null,
    null,
    null,
    .{ .container = .{ .contents = null, .volume_limit = null, .cubic_volume_limit = .{ .unit = .foot, .count = 1.0 }, .weight_limit = .{ .unit = .pound, .count = 30.0 }, .item_limit = null, .item_bias = null, .valid_items = .{ .items = true, .fluids = false }, .outside_slots = true } },
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const barrel: Item = Item.compInit(
    "Barrel",
    .phb14,
    false,
    .{ .unit = .pound, .count = 70.0 },
    null,
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    "Capacity: 40 gallons of liquid or 4 cubic feet of solid material.",
    null,
    null,
    null,
    .{ .container = .{ .contents = null, .volume_limit = .{ .unit = .gallon, .count = 40.0 }, .cubic_volume_limit = .{ .unit = .foot, .count = 4.0 }, .weight_limit = null, .item_limit = null, .item_bias = null, .valid_items = .{ .items = true, .fluids = true }, .outside_slots = false } },
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const basket: Item = Item.compInit(
    "Basket",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    null,
    null,
    .{ .currency = .silver, .count = 4 },
    null,
    "Capacity: 2 cubic feet or 40 pounds of gear.",
    null,
    null,
    null,
    .{ .container = .{ .contents = null, .volume_limit = null, .cubic_volume_limit = .{ .unit = .foot, .count = 2.0 }, .weight_limit = .{ .unit = .pound, .count = 40.0 }, .item_limit = null, .item_bias = null, .valid_items = .{ .items = true, .fluids = false }, .outside_slots = false } },
    .{ .cost = .{ .currency = .silver, .count = 4 }, .count = 1, .wrapping_container = null },
);

pub const bucket: Item = Item.compInit(
    "Bucket",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    null,
    null,
    .{ .currency = .copper, .count = 5 },
    null,
    "Capacity: 3 gallons of liquid or 1/2 cubic foot of solid material.",
    null,
    null,
    null,
    .{ .container = .{ .contents = null, .volume_limit = .{ .unit = .gallon, .count = 3.0 }, .cubic_volume_limit = .{ .unit = .foot, .count = 0.5 }, .weight_limit = null, .item_limit = null, .item_bias = null, .valid_items = .{ .items = true, .fluids = true }, .outside_slots = false } },
    .{ .cost = .{ .currency = .copper, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const crossbow_bolt_case: Item = Item.compInit(
    "Crossbow Bolt Case",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    "Capacity: 20 crossbow bolts.",
    null,
    null,
    null,
    .{ .container = .{ .contents = null, .volume_limit = null, .cubic_volume_limit = null, .weight_limit = null, .item_limit = 20, .item_bias = &.{weapons.crossbow_bolt.hash}, .valid_items = .{ .items = true, .fluids = false }, .outside_slots = false } },
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const map_scroll_case: Item = Item.compInit(
    "Map or Scroll Case",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    "Capacity: ten rolled sheets of paper or five rolled sheets of parchment.",
    null,
    null,
    null,
    .{ .container = .{ .contents = null, .volume_limit = null, .cubic_volume_limit = null, .weight_limit = null, .item_limit = 10, .item_bias = &.{ parchment.hash, paper.hash }, .valid_items = .{ .items = true, .fluids = false }, .outside_slots = false } },
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const chest: Item = Item.compInit(
    "Chest",
    .phb14,
    false,
    .{ .unit = .pound, .count = 25.0 },
    null,
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    "Capacity: 12 cubic feet or 300 pounds of gear.",
    null,
    null,
    null,
    .{ .container = .{ .contents = null, .volume_limit = null, .cubic_volume_limit = .{ .unit = .foot, .count = 12.0 }, .weight_limit = .{ .unit = .pound, .count = 300.0 }, .item_limit = null, .item_bias = null, .valid_items = .{ .items = true, .fluids = false }, .outside_slots = false } },
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const flask: Item = Item.compInit(
    "Flask",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    .{ .unit = .pint, .count = 1 },
    null,
    .{ .currency = .copper, .count = 2 },
    null,
    "Capacity: 1 pint of liquid.",
    null,
    null,
    null,
    .{ .fluid_container = .{ .fluid = null, .volume_limit = .{ .unit = .pint, .count = 1.0 }, .weight_full = null, .volume_of_contents = null } },
    .{ .cost = .{ .currency = .copper, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const glass_bottle: Item = Item.compInit(
    "Glass Bottle",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .pint, .count = 1.5 },
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    "Capacity: 1.5 pints of liquid.",
    null,
    null,
    null,
    .{ .fluid_container = .{ .fluid = null, .volume_limit = .{ .unit = .pint, .count = 1.5 }, .weight_full = null, .volume_of_contents = null } },
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const jug: Item = Item.compInit(
    "Jug",
    .phb14,
    false,
    .{ .unit = .pound, .count = 4.0 },
    .{ .unit = .gallon, .count = 1 },
    null,
    .{ .currency = .copper, .count = 2 },
    null,
    "Capacity: 1 gallon of liquid.",
    null,
    null,
    null,
    .{ .fluid_container = .{ .fluid = null, .volume_limit = .{ .unit = .gallon, .count = 1.0 }, .weight_full = null, .volume_of_contents = null } },
    .{ .cost = .{ .currency = .copper, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const iron_pot: Item = Item.compInit(
    "Iron Pot",
    .phb14,
    false,
    .{ .unit = .pound, .count = 10.0 },
    .{ .unit = .gallon, .count = 1 },
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    "Capacity: 1 gallon of liquid.",
    null,
    null,
    null,
    .{ .fluid_container = .{ .fluid = null, .volume_limit = .{ .unit = .gallon, .count = 1.0 }, .weight_full = null, .volume_of_contents = null } },
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const quiver: Item = Item.compInit(
    "Quiver",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    "Capacity: 20 arrows.",
    null,
    null,
    null,
    .{ .container = .{ .contents = null, .volume_limit = null, .cubic_volume_limit = null, .weight_limit = null, .item_limit = 20, .item_bias = &.{weapons.arrow.hash}, .valid_items = .{ .items = true, .fluids = false }, .outside_slots = false } },
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const sack: Item = Item.compInit(
    "Sack",
    .phb14,
    false,
    .{ .unit = .pound, .count = 0.5 },
    null,
    null,
    .{ .currency = .copper, .count = 1 },
    null,
    "Capacity: 1 cubic foot or 30 pounds of gear.",
    null,
    null,
    null,
    .{ .container = .{ .contents = null, .volume_limit = null, .cubic_volume_limit = .{ .unit = .foot, .count = 1.0 }, .weight_limit = .{ .unit = .pound, .count = 30.0 }, .item_limit = null, .item_bias = null, .valid_items = .{ .items = true, .fluids = false }, .outside_slots = false } },
    .{ .cost = .{ .currency = .copper, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const vial: Item = Item.compInit(
    "Vial",
    .phb14,
    false,
    null,
    .{ .unit = .ounce, .count = 4 },
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    "Capacity: 4 ounces of liquid.",
    null,
    null,
    null,
    .{ .fluid_container = .{ .fluid = null, .volume_limit = .{ .unit = .ounce, .count = 4.0 }, .weight_full = null, .volume_of_contents = null } },
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const water: Item = Item.compInit(
    "Water",
    .phb14,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .fluid = .{ .weight = null, .default_container = waterskin.hash } },
    null,
);

pub const waterskin: Item = Item.compInit(
    "Waterskin",
    .phb14,
    false,
    null,
    .{ .unit = .pint, .count = 4 },
    null,
    .{ .currency = .silver, .count = 2 },
    null,
    "Capacity: 4 pints of liquid. Listed weight is 5 pounds when full.",
    null,
    null,
    null,
    .{ .fluid_container = .{ .fluid = null, .volume_limit = .{ .unit = .pint, .count = 4.0 }, .weight_full = .{ .unit = .pound, .count = 5.0 }, .volume_of_contents = null } },
    .{ .cost = .{ .currency = .silver, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const acid: Item = Item.compInit(
    "Acid",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .gold, .count = 25 },
    null,
    null,
    "Can be splashed or thrown as an improvised ranged weapon; on a hit it deals 2d6 acid damage.",
    null,
    null,
    .{ .fluid = .{ .default_container = vial.hash, .weight = .{ .unit = .pound, .count = 1.0 } } },
    .{ .cost = .{ .currency = .gold, .count = 25 }, .count = 1, .wrapping_container = vial.hash },
);

pub const alchemists_fire: Item = Item.compInit(
    "Alchemist's Fire",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .gold, .count = 50 },
    null,
    null,
    "A sticky liquid that ignites on exposure to air and can be thrown; a hit causes ongoing fire until extinguished.",
    null,
    null,
    .{ .fluid = .{ .default_container = flask.hash, .weight = .{ .unit = .pound, .count = 1.0 } } },
    .{ .cost = .{ .currency = .gold, .count = 50 }, .count = 1, .wrapping_container = flask.hash },
);

pub const antitoxin: Item = Item.compInit(
    "Antitoxin",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .gold, .count = 50 },
    null,
    null,
    "Drinking it grants temporary advantage on saving throws against poison, except for undead and constructs.",
    null,
    null,
    .{ .fluid = .{ .default_container = vial.hash, .weight = null } },
    .{ .cost = .{ .currency = .gold, .count = 50 }, .count = 1, .wrapping_container = vial.hash },
);

pub const ball_bearing: Item = Item.compInit(
    "Ball Bearing",
    .phb14,
    false,
    .{ .unit = .pound, .count = 0.002 },
    null,
    null,
    null,
    null,
    null,
    "A single steel ball bearing. The standard shop bundle contains 1,000 in a pouch.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1000, .wrapping_container = pouch.hash },
);

pub const caltrop: Item = Item.compInit(
    "Caltrop",
    .phb14,
    false,
    .{ .unit = .pound, .count = 0.1 },
    null,
    null,
    null,
    null,
    null,
    "A single caltrop. The standard shop bundle contains 20 in a pouch.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 20, .wrapping_container = pouch.hash },
);

pub const climbers_kit: Item = Item.compInit(
    "Climber's Kit",
    .phb14,
    false,
    .{ .unit = .pound, .count = 12.0 },
    null,
    null,
    .{ .currency = .gold, .count = 25 },
    null,
    null,
    "Includes specialized pitons, boot tips, gloves, and a harness for anchoring a climber.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 25 }, .count = 1, .wrapping_container = null },
);

pub const crowbar: Item = Item.compInit(
    "Crowbar",
    .phb14,
    false,
    .{ .unit = .pound, .count = 5.0 },
    null,
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    null,
    "Provides advantage on Strength checks when its leverage can be applied.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const healers_kit: Item = Item.compInit(
    "Healer's Kit",
    .phb14,
    false,
    .{ .unit = .pound, .count = 3.0 },
    null,
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    null,
    "A ten-use kit of bandages, salves, and splints; a use can stabilize a creature at 0 hit points.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const holy_water: Item = Item.compInit(
    "Holy Water",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .gold, .count = 25 },
    null,
    null,
    "Can be splashed or thrown; it deals radiant damage to fiends and undead.",
    null,
    null,
    .{ .fluid = .{ .default_container = flask.hash, .weight = .{ .unit = .pound, .count = 1.0 } } },
    .{ .cost = .{ .currency = .gold, .count = 25 }, .count = 1, .wrapping_container = flask.hash },
);

pub const hunting_trap: Item = Item.compInit(
    "Hunting Trap",
    .phb14,
    false,
    .{ .unit = .pound, .count = 25.0 },
    null,
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    null,
    "A chained, pressure-triggered steel trap that can injure and restrain a creature until it escapes.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const lamp: Item = Item.compInit(
    "Lamp",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .silver, .count = 5 },
    null,
    null,
    "Burns oil for about 6 hours, producing bright light nearby and dim light farther out.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .silver, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const bullseye_lantern: Item = Item.compInit(
    "Bullseye Lantern",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    null,
    null,
    .{ .currency = .gold, .count = 10 },
    null,
    null,
    "Burns oil for about 6 hours and projects a long cone of bright and dim light.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = null },
);

pub const hooded_lantern: Item = Item.compInit(
    "Hooded Lantern",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    null,
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    null,
    "Burns oil for about 6 hours; its hood can reduce the light to a small dim area.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const oil: Item = Item.compInit(
    "Oil",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .silver, .count = 1 },
    null,
    null,
    "A pint of lamp oil that can also be splashed, thrown, or poured and ignited.",
    null,
    null,
    .{ .fluid = .{ .default_container = flask.hash, .weight = .{ .unit = .pound, .count = 1.0 } } },
    .{ .cost = .{ .currency = .silver, .count = 1 }, .count = 1, .wrapping_container = flask.hash },
);

pub const basic_poison: Item = Item.compInit(
    "Basic Poison",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .gold, .count = 100 },
    null,
    null,
    "Can coat one slashing or piercing weapon or up to three pieces of ammunition for a short time.",
    null,
    null,
    .{ .fluid = .{ .default_container = vial.hash, .weight = null } },
    .{ .cost = .{ .currency = .gold, .count = 100 }, .count = 1, .wrapping_container = vial.hash },
);

pub const potion_of_healing: Item = Item.compInit(
    "Potion of Healing",
    .phb14,
    true,
    null,
    null,
    null,
    .{ .currency = .gold, .count = 50 },
    .common,
    null,
    "A common healing potion.",
    null,
    null,
    .{ .potion = .{ .default_container = vial.hash, .weight = .{ .unit = .pound, .count = 0.5 } } },
    .{ .cost = .{ .currency = .gold, .count = 50 }, .count = 1, .wrapping_container = vial.hash },
);

pub const tinderbox: Item = Item.compInit(
    "Tinderbox",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .silver, .count = 5 },
    null,
    null,
    "Contains flint, fire steel, and tinder for starting fires.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .silver, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const torch: Item = Item.compInit(
    "Torch",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .copper, .count = 1 },
    null,
    null,
    "Burns for about 1 hour, providing light; a burning torch can deal 1 fire damage as an improvised melee attack.",
    null,
    null,
    null,
    .{ .cost = .{ .currency = .copper, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const common_clothes: Item = Item.compInit(
    "Common Clothes",
    .phb14,
    false,
    .{ .unit = .pound, .count = 3.0 },
    null,
    null,
    .{ .currency = .silver, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .silver, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const costume: Item = Item.compInit(
    "Costume",
    .phb14,
    false,
    .{ .unit = .pound, .count = 4.0 },
    null,
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const fine_clothes: Item = Item.compInit(
    "Fine Clothes",
    .phb14,
    false,
    .{ .unit = .pound, .count = 6.0 },
    null,
    null,
    .{ .currency = .gold, .count = 15 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 15 }, .count = 1, .wrapping_container = null },
);

pub const robes: Item = Item.compInit(
    "Robes",
    .phb14,
    false,
    .{ .unit = .pound, .count = 4.0 },
    null,
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const travelers_clothes: Item = Item.compInit(
    "Traveler's Clothes",
    .phb14,
    false,
    .{ .unit = .pound, .count = 4.0 },
    null,
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const arcane_crystal: Item = Item.compInit(
    "Arcane Focus - Crystal",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .gold, .count = 10 },
    null,
    "Arcane spellcasting focus.",
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = null },
);

pub const arcane_orb: Item = Item.compInit(
    "Arcane Focus - Orb",
    .phb14,
    false,
    .{ .unit = .pound, .count = 3.0 },
    null,
    null,
    .{ .currency = .gold, .count = 20 },
    null,
    "Arcane spellcasting focus.",
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 20 }, .count = 1, .wrapping_container = null },
);

pub const arcane_rod: Item = Item.compInit(
    "Arcane Focus - Rod",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    null,
    null,
    .{ .currency = .gold, .count = 10 },
    null,
    "Arcane spellcasting focus.",
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = null },
);

pub const arcane_staff: Item = Item.compInit(
    "Arcane Focus - Staff",
    .phb14,
    false,
    .{ .unit = .pound, .count = 4.0 },
    null,
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    "Arcane spellcasting focus.",
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const arcane_wand: Item = Item.compInit(
    "Arcane Focus - Wand",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .gold, .count = 10 },
    null,
    "Arcane spellcasting focus.",
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = null },
);

pub const sprig_of_mistletoe: Item = Item.compInit(
    "Sprig of Mistletoe",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    "Druidic spellcasting focus.",
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const druidic_totem: Item = Item.compInit(
    "Totem",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    "Druidic spellcasting focus.",
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const wooden_staff: Item = Item.compInit(
    "Wooden Staff",
    .phb14,
    false,
    .{ .unit = .pound, .count = 4.0 },
    null,
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    "Druidic spellcasting focus.",
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const yew_wand: Item = Item.compInit(
    "Yew Wand",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .gold, .count = 10 },
    null,
    "Druidic spellcasting focus.",
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = null },
);

pub const holy_amulet: Item = Item.compInit(
    "Amulet",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    null,
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    "Holy symbol suitable for use as a spellcasting focus.",
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const holy_emblem: Item = Item.compInit(
    "Emblem",
    .phb14,
    false,
    null,
    null,
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    "Holy symbol suitable for use as a spellcasting focus.",
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const holy_reliquary: Item = Item.compInit(
    "Reliquary",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    null,
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    "Holy symbol suitable for use as a spellcasting focus.",
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const fargab: Item = Item.compInit(
    "Fargab",
    .dsotdq,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    "A paired, backpack-sized radio device capable of sending a short spoken message to its matched unit within 18 miles.",
    null,
    null,
    null,
    null,
);

pub const narycrash: Item = Item.compInit(
    "Narycrash",
    .dsotdq,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    "A backpack-sized balloon parachute that can slow a fall when deployed, with a chance of failing near the ground.",
    null,
    null,
    null,
    null,
);

pub const soap: Item = Item.compInit(
    "Soap",
    .phb14,
    false,
    null,
    null,
    null,
    null,
    null,
    null,
    "Soap included in the Diplomat's Pack. The cited adventuring-gear page does not list a standalone price.",
    null,
    null,
    null,
    null,
);

pub const item_arr = [_]Item{
    soap,
    string_10_ft,
    alms_box,
    incense_block,
    censer,
    vestments,
    small_bag_of_sand,
    small_knife,
    abacus,
    bedroll,
    bell,
    blanket,
    block_and_tackle,
    book,
    candle,
    chain_10_ft,
    chalk,
    component_pouch,
    fishing_tackle,
    grappling_hook,
    hammer,
    hourglass,
    ink_bottle_1_oz,
    ink,
    ink_pen,
    ladder_10_ft,
    lock,
    magnifying_glass,
    manacles,
    mess_kit,
    miners_pick,
    paper,
    parchment,
    pouch,
    perfume,
    piton,
    pole_10_ft,
    portable_ram,
    ration,
    hempen_rope_50_ft,
    silk_rope_50_ft,
    sealing_wax,
    shovel,
    signal_whistle,
    signet_ring,
    sledgehammer,
    spellbook,
    iron_spike,
    spyglass,
    two_person_tent,
    whetstone,
    backpack,
    barrel,
    basket,
    bucket,
    crossbow_bolt_case,
    map_scroll_case,
    chest,
    flask,
    glass_bottle,
    jug,
    iron_pot,
    quiver,
    sack,
    vial,
    water,
    waterskin,
    acid,
    alchemists_fire,
    antitoxin,
    ball_bearing,
    caltrop,
    climbers_kit,
    crowbar,
    healers_kit,
    holy_water,
    hunting_trap,
    lamp,
    bullseye_lantern,
    hooded_lantern,
    oil,
    basic_poison,
    potion_of_healing,
    tinderbox,
    torch,
    common_clothes,
    costume,
    fine_clothes,
    robes,
    travelers_clothes,
    arcane_crystal,
    arcane_orb,
    arcane_rod,
    arcane_staff,
    arcane_wand,
    sprig_of_mistletoe,
    druidic_totem,
    wooden_staff,
    yew_wand,
    holy_amulet,
    holy_emblem,
    holy_reliquary,
    fargab,
    narycrash,
};
