const items = @import("items.zig");
const Item = items.Item;
const dice = @import("dice.zig");

// ============================================================================
// Ammunition
// ============================================================================

// Each definition is one physical piece. The PHB lists ammunition in bundles,
// so shop_entry stores the bundle price/count. value stays null because the
// source table does not provide a per-piece price.

pub const arrow: Item = Item.compInit(
    "Arrow",
    .phb14,
    false,
    .{ .unit = .pound, .count = 0.05 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 20, .wrapping_container = null },
);

pub const blowgun_needle: Item = Item.compInit(
    "Blowgun Needle",
    .phb14,
    false,
    .{ .unit = .pound, .count = 0.02 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 50, .wrapping_container = null },
);

pub const crossbow_bolt: Item = Item.compInit(
    "Crossbow Bolt",
    .phb14,
    false,
    .{ .unit = .pound, .count = 0.075 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 20, .wrapping_container = null },
);

pub const sling_bullet: Item = Item.compInit(
    "Sling Bullet",
    .phb14,
    false,
    .{ .unit = .pound, .count = 0.075 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    .{ .cost = .{ .currency = .copper, .count = 4 }, .count = 20, .wrapping_container = null },
);

// ============================================================================
// Simple Melee Weapons
// ============================================================================

pub const club: Item = Item.compInit(
    "Club",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .silver, .count = 1 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .bludgeoning },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d4 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = true,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .silver, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const dagger: Item = Item.compInit(
    "Dagger",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d4 } },
            .properties = .{
                .finesse = true,
                .heavy = false,
                .light = true,
                .loading = false,
                .range = .{ .normal = 20, .max = 60 },
                .reach = false,
                .special = false,
                .thrown = true,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const greatclub: Item = Item.compInit(
    "Greatclub",
    .phb14,
    false,
    .{ .unit = .pound, .count = 10.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .silver, .count = 2 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .bludgeoning },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d8 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = true,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .silver, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const handaxe: Item = Item.compInit(
    "Handaxe",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .slashing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d6 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = true,
                .loading = false,
                .range = .{ .normal = 20, .max = 60 },
                .reach = false,
                .special = false,
                .thrown = true,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const javelin: Item = Item.compInit(
    "Javelin",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .silver, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d6 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = .{ .normal = 30, .max = 120 },
                .reach = false,
                .special = false,
                .thrown = true,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .silver, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const light_hammer: Item = Item.compInit(
    "Light Hammer",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .bludgeoning },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d4 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = true,
                .loading = false,
                .range = .{ .normal = 20, .max = 60 },
                .reach = false,
                .special = false,
                .thrown = true,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const mace: Item = Item.compInit(
    "Mace",
    .phb14,
    false,
    .{ .unit = .pound, .count = 4.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .bludgeoning },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d6 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const quarterstaff: Item = Item.compInit(
    "Quarterstaff",
    .phb14,
    false,
    .{ .unit = .pound, .count = 4.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .silver, .count = 2 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .bludgeoning },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d6 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = true,
                .versatile_dice = .{ .count = 1, .dice = &dice.d8 },
            },
        },
    },
    .{ .cost = .{ .currency = .silver, .count = 2 }, .count = 1, .wrapping_container = null },
);

pub const sickle: Item = Item.compInit(
    "Sickle",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .slashing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d4 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = true,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const spear: Item = Item.compInit(
    "Spear",
    .phb14,
    false,
    .{ .unit = .pound, .count = 3.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d6 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = .{ .normal = 20, .max = 60 },
                .reach = false,
                .special = false,
                .thrown = true,
                .two_handed = false,
                .versatile = true,
                .versatile_dice = .{ .count = 1, .dice = &dice.d8 },
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

// ============================================================================
// Simple Ranged Weapons
// ============================================================================

pub const light_crossbow: Item = Item.compInit(
    "Light Crossbow",
    .phb14,
    false,
    .{ .unit = .pound, .count = 5.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 25 },
    null,
    null,
    null,
    null,
    null,
    .{
        .ranged_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d8 } },
            .properties = .{
                .ammunition = true,
                .ammo = crossbow_bolt.hash,
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = true,
                .range = .{ .normal = 80, .max = 320 },
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = true,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 25 }, .count = 1, .wrapping_container = null },
);

pub const dart: Item = Item.compInit(
    "Dart",
    .phb14,
    false,
    .{ .unit = .pound, .count = 0.25 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .copper, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    .{
        .ranged_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d4 } },
            .properties = .{
                .ammunition = false,
                .ammo = null,
                .finesse = true,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = .{ .normal = 20, .max = 60 },
                .reach = false,
                .special = false,
                .thrown = true,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .copper, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const shortbow: Item = Item.compInit(
    "Shortbow",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 25 },
    null,
    null,
    null,
    null,
    null,
    .{
        .ranged_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d6 } },
            .properties = .{
                .ammunition = true,
                .ammo = arrow.hash,
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = .{ .normal = 80, .max = 320 },
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = true,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 25 }, .count = 1, .wrapping_container = null },
);

pub const sling: Item = Item.compInit(
    "Sling",
    .phb14,
    false,
    .{ .unit = .pound, .count = 0.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .silver, .count = 1 },
    null,
    null,
    null,
    null,
    null,
    .{
        .ranged_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .bludgeoning },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d4 } },
            .properties = .{
                .ammunition = true,
                .ammo = sling_bullet.hash,
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = .{ .normal = 30, .max = 120 },
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .silver, .count = 1 }, .count = 1, .wrapping_container = null },
);

// ============================================================================
// Martial Melee Weapons
// ============================================================================

pub const battleaxe: Item = Item.compInit(
    "Battleaxe",
    .phb14,
    false,
    .{ .unit = .pound, .count = 4.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 10 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .slashing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d8 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = true,
                .versatile_dice = .{ .count = 1, .dice = &dice.d10 },
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = null },
);

pub const flail: Item = Item.compInit(
    "Flail",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 10 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .bludgeoning },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d8 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = null },
);

pub const glaive: Item = Item.compInit(
    "Glaive",
    .phb14,
    false,
    .{ .unit = .pound, .count = 6.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 20 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .slashing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d10 } },
            .properties = .{
                .finesse = false,
                .heavy = true,
                .light = false,
                .loading = false,
                .range = null,
                .reach = true,
                .special = false,
                .thrown = false,
                .two_handed = true,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 20 }, .count = 1, .wrapping_container = null },
);

pub const greataxe: Item = Item.compInit(
    "Greataxe",
    .phb14,
    false,
    .{ .unit = .pound, .count = 7.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 30 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .slashing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d12 } },
            .properties = .{
                .finesse = false,
                .heavy = true,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = true,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 30 }, .count = 1, .wrapping_container = null },
);

pub const greatsword: Item = Item.compInit(
    "Greatsword",
    .phb14,
    false,
    .{ .unit = .pound, .count = 6.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 50 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .slashing },
            .damage = .{ .roll = .{ .count = 2, .dice = &dice.d6 } },
            .properties = .{
                .finesse = false,
                .heavy = true,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = true,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 50 }, .count = 1, .wrapping_container = null },
);

pub const halberd: Item = Item.compInit(
    "Halberd",
    .phb14,
    false,
    .{ .unit = .pound, .count = 6.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 20 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .slashing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d10 } },
            .properties = .{
                .finesse = false,
                .heavy = true,
                .light = false,
                .loading = false,
                .range = null,
                .reach = true,
                .special = false,
                .thrown = false,
                .two_handed = true,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 20 }, .count = 1, .wrapping_container = null },
);

pub const lance: Item = Item.compInit(
    "Lance",
    .phb14,
    false,
    .{ .unit = .pound, .count = 6.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 10 },
    null,
    null,
    "Attacks against creatures within 5 feet have disadvantage. A lance requires two hands while its wielder is not mounted.",
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d12 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = null,
                .reach = true,
                .special = true,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = null },
);

pub const longsword: Item = Item.compInit(
    "Longsword",
    .phb14,
    false,
    .{ .unit = .pound, .count = 3.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 15 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .slashing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d8 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = true,
                .versatile_dice = .{ .count = 1, .dice = &dice.d10 },
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 15 }, .count = 1, .wrapping_container = null },
);

pub const maul: Item = Item.compInit(
    "Maul",
    .phb14,
    false,
    .{ .unit = .pound, .count = 10.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 10 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .bludgeoning },
            .damage = .{ .roll = .{ .count = 2, .dice = &dice.d6 } },
            .properties = .{
                .finesse = false,
                .heavy = true,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = true,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = null },
);

pub const morningstar: Item = Item.compInit(
    "Morningstar",
    .phb14,
    false,
    .{ .unit = .pound, .count = 4.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 15 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d8 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 15 }, .count = 1, .wrapping_container = null },
);

pub const pike: Item = Item.compInit(
    "Pike",
    .phb14,
    false,
    .{ .unit = .pound, .count = 18.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d10 } },
            .properties = .{
                .finesse = false,
                .heavy = true,
                .light = false,
                .loading = false,
                .range = null,
                .reach = true,
                .special = false,
                .thrown = false,
                .two_handed = true,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const rapier: Item = Item.compInit(
    "Rapier",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 25 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d8 } },
            .properties = .{
                .finesse = true,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 25 }, .count = 1, .wrapping_container = null },
);

pub const scimitar: Item = Item.compInit(
    "Scimitar",
    .phb14,
    false,
    .{ .unit = .pound, .count = 3.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 25 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .slashing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d6 } },
            .properties = .{
                .finesse = true,
                .heavy = false,
                .light = true,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 25 }, .count = 1, .wrapping_container = null },
);

pub const shortsword: Item = Item.compInit(
    "Shortsword",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 10 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d6 } },
            .properties = .{
                .finesse = true,
                .heavy = false,
                .light = true,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = null },
);

pub const trident: Item = Item.compInit(
    "Trident",
    .phb14,
    false,
    .{ .unit = .pound, .count = 4.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d6 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = .{ .normal = 20, .max = 60 },
                .reach = false,
                .special = false,
                .thrown = true,
                .two_handed = false,
                .versatile = true,
                .versatile_dice = .{ .count = 1, .dice = &dice.d8 },
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const war_pick: Item = Item.compInit(
    "War Pick",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 5 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d8 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 5 }, .count = 1, .wrapping_container = null },
);

pub const warhammer: Item = Item.compInit(
    "Warhammer",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 15 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .bludgeoning },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d8 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = true,
                .versatile_dice = .{ .count = 1, .dice = &dice.d10 },
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 15 }, .count = 1, .wrapping_container = null },
);

pub const whip: Item = Item.compInit(
    "Whip",
    .phb14,
    false,
    .{ .unit = .pound, .count = 3.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 2 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .slashing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d4 } },
            .properties = .{
                .finesse = true,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = null,
                .reach = true,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 2 }, .count = 1, .wrapping_container = null },
);

// ============================================================================
// Martial Ranged Weapons
// ============================================================================

pub const blowgun: Item = Item.compInit(
    "Blowgun",
    .phb14,
    false,
    .{ .unit = .pound, .count = 1.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 10 },
    null,
    null,
    null,
    null,
    null,
    .{
        .ranged_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .flat = 1 },
            .properties = .{
                .ammunition = true,
                .ammo = blowgun_needle.hash,
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = true,
                .range = .{ .normal = 25, .max = 100 },
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 10 }, .count = 1, .wrapping_container = null },
);

pub const hand_crossbow: Item = Item.compInit(
    "Hand Crossbow",
    .phb14,
    false,
    .{ .unit = .pound, .count = 3.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 75 },
    null,
    null,
    null,
    null,
    null,
    .{
        .ranged_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d6 } },
            .properties = .{
                .ammunition = true,
                .ammo = crossbow_bolt.hash,
                .finesse = false,
                .heavy = false,
                .light = true,
                .loading = true,
                .range = .{ .normal = 30, .max = 120 },
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 75 }, .count = 1, .wrapping_container = null },
);

pub const heavy_crossbow: Item = Item.compInit(
    "Heavy Crossbow",
    .phb14,
    false,
    .{ .unit = .pound, .count = 18.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 50 },
    null,
    null,
    null,
    null,
    null,
    .{
        .ranged_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d10 } },
            .properties = .{
                .ammunition = true,
                .ammo = crossbow_bolt.hash,
                .finesse = false,
                .heavy = true,
                .light = false,
                .loading = true,
                .range = .{ .normal = 100, .max = 400 },
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = true,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 50 }, .count = 1, .wrapping_container = null },
);

pub const longbow: Item = Item.compInit(
    "Longbow",
    .phb14,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 50 },
    null,
    null,
    null,
    null,
    null,
    .{
        .ranged_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d8 } },
            .properties = .{
                .ammunition = true,
                .ammo = arrow.hash,
                .finesse = false,
                .heavy = true,
                .light = false,
                .loading = false,
                .range = .{ .normal = 150, .max = 600 },
                .reach = false,
                .special = false,
                .thrown = false,
                .two_handed = true,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 50 }, .count = 1, .wrapping_container = null },
);

pub const net: Item = Item.compInit(
    "Net",
    .phb14,
    false,
    .{ .unit = .pound, .count = 3.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    null,
    "A hit restrains an eligible Large-or-smaller creature until it is freed or the net is destroyed. Attacking with a net limits that action, bonus action, or reaction to one attack.",
    null,
    null,
    .{
        .ranged_weapon = .{
            .weapon_category = .martial,
            .damage_type = null,
            .damage = null,
            .properties = .{
                .ammunition = false,
                .ammo = null,
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = .{ .normal = 5, .max = 15 },
                .reach = false,
                .special = true,
                .thrown = true,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

// ============================================================================
// Setting-Specific Weapons
// ============================================================================

pub const yklwa: Item = Item.compInit(
    "Yklwa",
    .toa,
    false,
    .{ .unit = .pound, .count = 3.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    null,
    null,
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .simple,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d8 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = .{ .normal = 10, .max = 30 },
                .reach = false,
                .special = false,
                .thrown = true,
                .two_handed = false,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const hoopak: Item = Item.compInit(
    "Hoopak",
    .dsotdq,
    false,
    .{ .unit = .pound, .count = 2.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 1 },
    null,
    null,
    "The melee mode deals piercing damage. It can alternatively be used as a martial ranged weapon with sling bullets, a 40/160-foot range, and 1d4 bludgeoning damage; its ammunition property is ignored for melee attacks.",
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .piercing },
            .damage = .{ .roll = .{ .count = 1, .dice = &dice.d6 } },
            .properties = .{
                .finesse = true,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = .{ .normal = 40, .max = 160 },
                .reach = false,
                .special = true,
                .thrown = false,
                .two_handed = true,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 1 }, .count = 1, .wrapping_container = null },
);

pub const double_bladed_scimitar: Item = Item.compInit(
    "Double-Bladed Scimitar",
    .erlw,
    false,
    .{ .unit = .pound, .count = 6.0 },
    .{ .unit = .ounce, .count = 0.0 },
    null,
    .{ .currency = .gold, .count = 100 },
    null,
    null,
    "After attacking with this weapon as part of the Attack action, its wielder can make a bonus-action melee attack with the opposite end; that attack deals 1d4 slashing damage.",
    null,
    null,
    .{
        .melee_weapon = .{
            .weapon_category = .martial,
            .damage_type = .{ .physical = .slashing },
            .damage = .{ .roll = .{ .count = 2, .dice = &dice.d4 } },
            .properties = .{
                .finesse = false,
                .heavy = false,
                .light = false,
                .loading = false,
                .range = null,
                .reach = false,
                .special = true,
                .thrown = false,
                .two_handed = true,
                .versatile = false,
                .versatile_dice = null,
            },
        },
    },
    .{ .cost = .{ .currency = .gold, .count = 100 }, .count = 1, .wrapping_container = null },
);

// ============================================================================
// Definition Arrays
// ============================================================================

pub const ammunition_arr = [_]Item{
    arrow,
    blowgun_needle,
    crossbow_bolt,
    sling_bullet,
};

pub const weapon_arr = [_]Item{
    club,
    dagger,
    greatclub,
    handaxe,
    javelin,
    light_hammer,
    mace,
    quarterstaff,
    sickle,
    spear,
    light_crossbow,
    dart,
    shortbow,
    sling,
    battleaxe,
    flail,
    glaive,
    greataxe,
    greatsword,
    halberd,
    lance,
    longsword,
    maul,
    morningstar,
    pike,
    rapier,
    scimitar,
    shortsword,
    trident,
    war_pick,
    warhammer,
    whip,
    blowgun,
    hand_crossbow,
    heavy_crossbow,
    longbow,
    net,
    yklwa,
    hoopak,
    double_bladed_scimitar,
};
